<?php

return [
    'logo' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4i0SKdX5JO9H3Pe4vI786Xj8So_TA9zUTZ4R097EjnhdEwt9euvjghKVAQbuWNZOnWKegqGRtIj7bWdWTABeOCVGvgqCtl4OppHZ71X82iMkgRgEWdKMZMXiPDuHwMM5f7UAf8wn_Dcty176WJHxAh1BsnTXi9kCZAEZyD_o9WhYcyg5Qxi2AAi7V4aVrxPhb_18NGrefCA7dMbODRwCd6jpUi3l8bTnyBbj1fE0FhOpSttOP6j9N',
    'hero' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnvteF7b-Qn3ep-Jkr64MCqfgnkTTg8bYxHReAfYgv8CpZHYXr5MhCNvvqMxcccVrOmmA49AM6Y3cThW3VEH2ilTsFfXO7fsJWUYGEj5SkH2I1jROOnvSiaSQBpVE1zTzPXONm7zef3XGLXNyOWcsw2OCaxUC-HAUldpA8C7XRJjDWrIViu7YiAqARz97Q8kqjnLGx6lTPb8R_q175Nup1rNHidkpcdCFyDIZGbtsG0VFWjYCJAKtj',
    'categories' => [
        ['key' => 'grill', 'name' => 'مشويات ودجاج', 'en_name' => 'Masala Chicken', 'image' => 'images/categories/grill.png'],
        ['key' => 'cafe', 'name' => 'مشروبات وعصائر', 'en_name' => 'Soft Beverages', 'image' => 'images/categories/beverages.png'],
        ['key' => 'fries', 'name' => 'بطاطس ومقبلات', 'en_name' => 'French Fries', 'image' => 'images/categories/fries.png'],
        ['key' => 'burger', 'name' => 'برجر وساندويش', 'en_name' => 'Crispy Burgers', 'image' => 'images/categories/burger.png'],
        ['key' => 'shawarma', 'name' => 'شاورما وصاج', 'en_name' => 'Shawarma', 'image' => 'images/categories/shawarma.png'],
        ['key' => 'pizza', 'name' => 'بيتزا وفطائر', 'en_name' => 'Artisan Pizza', 'image' => 'images/categories/pizza.png'],
        ['key' => 'sweets', 'name' => 'حلويات وكنافة', 'en_name' => 'Sweet Treats', 'image' => 'images/categories/sweets.png'],
        ['key' => 'seafood', 'name' => 'أسماك وبحريات', 'en_name' => 'Seafood', 'image' => 'images/categories/seafood.png'],
    ],
    'cuisine_keywords' => [
        'palestinian' => ['فلسطين', 'مقلوبة', 'مسخن', 'قدرة', 'غزي'],
        'grill' => ['مشاوي', 'مشويات', 'طاجن', 'طواجن', 'كباب', 'شيش', 'دجاج', 'مسحب'],
        'seafood' => ['سمك', 'أسماك', 'بحري', 'بحريات', 'حبار', 'صيادية'],
        'shawarma' => ['شاورما', 'صاج'],
        'pizza' => ['بيتزا', 'فطائر', 'فطيرة'],
        'burger' => ['برجر', 'ساندويش', 'ساندوتش'],
        'fries' => ['بطاطس', 'مقبلات', 'فرايز', 'ودجز', 'سناك'],
        'breakfast' => ['فطور', 'مناقيش', 'منقيش', 'كرواسون'],
        'sweets' => ['حلويات', 'كنافة', 'كيك', 'تشيز'],
        'cafe' => ['كافيه', 'كافي', 'قهوة', 'لاتيه', 'اسبريسو', 'شاي', 'عصير', 'عصائر', 'مشروب', 'مشروبات'],
        'international' => ['عالمي', 'باستا', 'ستيك'],
    ],
    'covers' => [
        'مطعم دار الياسمين' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDc3uBJAXX0dnUlXEdlZMRdyA3HVAke91sfUJK78PxbBhYy8YvWhqlruSjIc2AdIHy54StktoAP9h2x4s9ILTRjgmpMhpIyeVZINZ0UWXfxX1Co40F6D1kD_f18xcALz1D1oqbV4d8AmA2gTEwF2vtv28F9fITmIS0vu_B3xP5f4HIpFvExinoesvOLQCRZdyJYVhYhdIKpFpRjZy85BiycImA0YI8i08cyOvibDTw2H-S1jo0LXiZ4',
        'كافي تِرا' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZ8TDlAchpL1W-1Cq6YSvmCC1vG_DJ9cAUeviNIzBfg53uB6uPMiJYDm_-WojLTLOCe2DTJ8MVJ_pK-TjUkLOb1Y1w_HSQoVwsfd8iSNlAFjJXUBy8NOpIDh4icDUmIcimuXYmMl3WsbDFwEPXJj3VkggG7-Uj0c01QqUMyAbZqdXD8xJa86JA6rHhemuphNjDK-5ybt3j019K5TX-mjBXyJnohArGQt5ebs6kW84nT3VsP4pSir5d',
        'مشاوي أبو العبد' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCmTAX3Qtlbb6ySzxImWKMyMKr0zdFp2Bqh22hlNIDE1Miqio8X4fezBT8SwNXQPvAav1DhST5KQaXzf114yIGK8F5xo-3P-d5-n2TmkdmVaUMR351gIbdLLhBK-IbX2dY6P5x8ZHQrDq7dW7kGCzFHaCdRxLhZrfonsRUYoaENXaJpFp-dtW33caAGkRGFDH5lGKlFZt6HjqE23vdMDbUQv8YnlMZPatRG_EGZRL0J_dPVZVoRrcqs',
        'كافي زمان' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuC73XeidkoWf1HHahiuN5JvgtyGZkv42uM4EHPKHAuElgZtiG9U89PSYyZ9q_HfP7Y41np94ySm9MQonJbhgqMAu_Yc9Q7Jtrsge8tzEl4tUcmXau2LiEI3Gi20_yFqZX-NI1rMJTYTZEo8MaGlFPU6vNNrxvE7CLH-6AEzBVeLTMJzz4j1anREFjucmik1yAARgArr3YfPdhR3OXA_LFxjN7aM2T3xdJtf2krdgxYNtRtD6MaWAl8l',
        'مطعم السمك الأزرق' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7PSlQp2g3Dl3OIWWrNXzZd7c0BxN-yVubkBPI6GYiya9KFz7_Mt0jcnhpjj1gvBseFcefx3T9Tr-pwOvqsgBF22hPbojJtukDGa9zctmzluXs6gB1YA3TEeEuzTFjkGPcXo7QOQDccdWqBA9VXgvUoJQNtOhO2mBGssqMMy07ghUKSsAv9holfgQERJTMvbSesSUOCh3hGSUEhQp4fceeUzcNBWEP35GZRf3Ad00dShbEKz2R3bD2',
    ],
    'cafe_cover' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZ8TDlAchpL1W-1Cq6YSvmCC1vG_DJ9cAUeviNIzBfg53uB6uPMiJYDm_-WojLTLOCe2DTJ8MVJ_pK-TjUkLOb1Y1w_HSQoVwsfd8iSNlAFjJXUBy8NOpIDh4icDUmIcimuXYmMl3WsbDFwEPXJj3VkggG7-Uj0c01QqUMyAbZqdXD8xJa86JA6rHhemuphNjDK-5ybt3j019K5TX-mjBXyJnohArGQt5ebs6kW84nT3VsP4pSir5d',
    'restaurant_cover' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAlq0fM6FTcG2uFVSN_0wBL8MrLETgJLcammvXkhzsK6ZMTSfcFcrNP1hXROpqjcVxPQFa4ZpD3lhOOXspz8LGMh5P59tVVX87Q98XVdXerAvMGZnOdXkl2L09A1T8u3v2ZPoa-C2ufsyVltZX9--O42HFPz9fcZcH-lpKHr6JdK3oapFTfGO8TgDI_zLPwo-3Dj6jTwIZ-RBboYttxTKmMVKEjpGq2R3oOS4Jm-jYixFq2XGu7bRG',
    'rewards' => [],
    'cuisines' => [
        'palestinian' => 'مأكولات فلسطينية',
        'grill' => 'مشاوي وطواجن',
        'seafood' => 'أسماك وبحريات',
        'shawarma' => 'شاورما وصاج',
        'pizza' => 'بيتزا وفطائر',
        'burger' => 'برجر وساندويش',
        'breakfast' => 'فطور ومناقيش',
        'sweets' => 'حلويات وكنافة',
        'cafe' => 'قهوة ومشروبات',
        'international' => 'مطبخ عالمي',
    ],
    'areas' => [
        ['key' => 'الرمال', 'label' => 'غزة • حي الرمال'],
        ['key' => 'تل الهوى', 'label' => 'غزة • تل الهوى'],
        ['key' => 'النصر', 'label' => 'غزة • شارع النصر'],
        ['key' => 'الشجاعية', 'label' => 'غزة • الشجاعية'],
        ['key' => 'البلدة القديمة', 'label' => 'غزة • البلدة القديمة'],
        ['key' => 'الميناء', 'label' => 'غزة • الميناء'],
        ['key' => 'دير البلح', 'label' => 'غزة • دير البلح'],
        ['key' => 'خانيونس', 'label' => 'غزة • خانيونس'],
    ],
    'app' => [
        'play_store_url' => env('PLAY_STORE_URL') ?: '#',
        'app_store_url' => env('APP_STORE_URL') ?: '#',
        'play_rating' => '4.5',
        'app_store_rating' => '4.8',
    ],
];
